name: Test setup-python

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Python version'
        default: '3.13t'
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: Quansight-Labs/setup-python@v5
        with:
          python-version: ${{ inputs.version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - run: python -VVV

      - run: |
          python -m pip install numpy
          python -c "import numpy; print(numpy.random.randn(10))"
