name: Test Upstream actions/setup-python

on:
  workflow_dispatch:
      inputs:
        version:
          description: 'Python version'
          required: true


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@5
        with:
          python-version: ${{ inputs.version }}

      - name: Display Python version 1
        run: python -c "import sys; print(sys.version)"

      - run: python -VVV

      - run: |
          python -m pip install numpy
          python -c "import numpy; print(numpy.random.randn(10))"
